config/routes.rb
Rails.application.routes.draw do

  devise_for :users#, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    match 'admin/make_admin' => 'admin#make_admin', as: :admin_make_admin, via: [:get]
    match 'admin/get_pass' => 'admin#get_pass', as: :admin_get_pass, via: [:get]

  resources :admin, only: [:edit, :update] do
    get :make_admin, :get_pass
  end

  resources :competitions do
    collection do
      get :select_team, :join_comp, :leave_comp
    end
  end

  resources :invites, only: [:new, :create, :destroy] do
    collection do
      get :mass_invite
    end
  end

  resources :members, only: [:destroy, :new, :create] do
    collection do
      get :mass_add
    end
    member do
      get :join
    end
  end

  resources :notifications, only: [:index, :show]

  resources :preferences, only: [:edit, :update]
  resources :programs

  resources :simulations, only: [:index, :new] do
    collection do
      get :team_skills, :remove_member, :search
    end
    member do
      get :user_stats
    end
  end

  resources :skills do
    collection do
      get :category_skills, :indi_skills
    end
  end

  resources :teams do
    collection do
      get :mine
      post :transfer
    end
  end

  resources :users do
    collection do
      get :dashboard, :edit_avatar, :edit_password
      post  :update_password
    end
    member do
      get :column_graph, :indi_graph, :skill_graph
    end
  end

  resources :user_skills, only: [:create, :update, :index] do
    collection do
      patch :update
    end
  end

  get 'welcome/home'
  get 'welcome/contact_us'
  get 'welcome/about_us'

  resources :yes_lists do
    collection do
      get :difficult_graph, :hated_graph
    end
    member do
      get :toggle
    end

  end

  root to: 'welcome#home'
end


####
# get 'yes_lists/:id/toggle' => 'yes_lists#toggle', as: :toggle_yes_lists, via: [:get]
# match 'difficult_graph/yes_lists' => 'yes_lists#difficult_graph', as: :difficult_graph_yes_lists, via: [:get]
# match 'hated_graph/yes_lists' => 'yes_lists#hated_graph', as: :hated_graph_yes_lists, via: [:get]


####
# stuff transfered under the resources blocks
# match 'team_skills/simulations' => 'simulations#team_skills', as: :simulations_team_skills, via: [:get]
# match 'search/simulations' => 'simulations#search', as: :simulations_search, via: [:get]
# match 'remove_member/simulations' => 'simulations#remove_member', as: :simulations_remove_member, via: [:get]
# match 'user_stats/:id/simulations' => 'simulations#user_stats', as: :simulations_user_stats, via: [:get]

# Additional routes.
# get 'members/:id/join' => 'members#join', as: :members_join, via: [:get]
# get 'welcome/home'
# get 'welcome/contact_us'
# get 'welcome/about_us'

# match 'users/:id/edit_password' => 'users#edit_password', as: :user_edit_password, via: [:get]
# match 'users/update_password' => 'users#update_password', as: :user_update_password, via: [:post]
# match 'user/dashboard' => 'users#dashboard', as: :user_dashboard, via: [:get]
# match 'user/edit_avatar' => 'users#edit_avatar', as: :user_edit_avatar, via: [:get]
# match 'column_graph/:id/users' => 'users#column_graph', as: :column_graph_users, via: [:get]
# match 'indi_graph/:id/users' => 'users#indi_graph', as: :indi_graph_users, via: [:get]

# match 'pie_chart/skills' => 'skills#pie_chart', as: :pie_chart_skills, via: [:get]
# get 'yes_lists/:id/toggle' => 'yes_lists#toggle', as: :toggle_yes_lists, via: [:get]
# match 'difficult_graph/yes_lists' => 'yes_lists#difficult_graph', as: :difficult_graph_yes_lists, via: [:get]
# match 'hated_graph/yes_lists' => 'yes_lists#hated_graph', as: :hated_graph_yes_lists, via: [:get]
# match 'select_team/competitions' => 'competitions#select_team', as: :select_team_competitions, via: [:get]
# match 'join_comp/competitions' => 'competitions#join_comp', as: :join_comp_competitions, via: [:get]
# match 'leave_comp/competitions' => 'competitions#leave_comp', as: :leave_comp_competitions, via: [:get]

# get 'mine/users' => 'users#mine', as: :teams_mine, via: [:get]

# match 'admin/make_admin' => 'admin#make_admin', as: :admin_make_admin, via: [:get]
# match 'admin/get_pass' => 'admin#get_pass', as: :admin_get_pass, via: [:get]

# match 'mass_invite/invites' => 'invites#mass_invite', as: :invites_mass_invite, via: [:get]


#####
  # Probably do not need any of this nonsense:-
  # match 'members/join' => 'members#join', as: :members_join, via: [:get]
  # match 'members/leave' => 'members#leave', as: :members_leave, via: [:get]
  # match 'invites/invite' => 'invites#invite', as: :invites_invite, via: [:get]
  # match 'invites/send' => 'invites#send', as: :invites_send, via: [:get]
  # match 'invites/reject' => 'invites#reject', as: :invites_reject, via: [:get]

  # UserSkills default routes list -> managed under 'resources'
  # get 'user_skills/index'
  # get 'user_skills/new'
  # match 'user_skills/create' => 'user_skills#create', as: :user_skills_create, via: [:post]
  # get 'user_skills/edit'
  # get 'user_skills/update'
  # get 'user_skills/destroy'

  # Competitions default routes list -> managed under 'resources'
  # get 'competitions/index'
  # get 'competitions/:id/show' => 'competitions#show', as: :competition, via: [:get]
  # get 'competitions/new'
  # match 'competitions/create' => 'competitions#create', as: :competitions_create, via: [:post]
  # get 'competitions/edit'
  # get 'competitions/update'
  # get 'competitions/destroy'

  # Users default routes list -> managed under 'resources'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/edit_password' => 'users#edit_password'

  # YesLists default routes list -> managed under 'resources'
  # get 'yes_lists/new'
  # get 'yes_lists/create'
  # get 'yes_lists/index'
  # get 'yes_lists/edit'
  # get 'yes_lists/update'
  # get 'yes_lists/destroy'

app/models/yes_list.rb
class YesList < ApplicationRecord
  belongs_to :user, :class_name => 'User'
  belongs_to :target, :class_name => 'User'


  def self.duplicate(ylist)
    where("user_id = ? AND target_id = ?", ylist.user.id, ylist.target.id) || false
  end

  def self.compatibility(members)
    data = Hash.new
    members.each do |m|
      data[m.name] = m.yes_lists.where(target:members,match:'NO') if m.yes_lists.where(target:members,match:'NO').present?
    end
    data
  end
  # def toggle
  #    unless !self.match
  #      self.match == 'YES' ? self.match = 'NO' : self.match = 'YES'
  #    end
  # end

end

app/controllers/yes_lists_controller.rb
class YesListsController < ApplicationController
  def new
    @yes_list = YesList.new
    @users = User.students.no_pref(current_user)
  end

  def create
    @yes_list = YesList.new(list_params)
    if YesList.duplicate(@yes_list).present?
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'This preference already exists.'
              render action: 'error'}
      end
    elsif @yes_list.save
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Saved.' }
      end
    end
  end

  def index
    @count = YesList.group(:user_id).count.count
    current_user.admin ? @users = search_params.paginate(page: params[:page], per_page: 20) : @yes_lists = YesList.where(user:current_user).paginate(page: params[:page], per_page: 20)
    @users = (User.students.no_pref(current_user).order(:fname) - [current_user]).paginate(page: params[:page], per_page:10) unless current_user.admin
  end

  def difficult_graph
    render json: User.difficult
  end
  def hated_graph
    render json: User.hated
  end

  def destroy
    @yes_list = YesList.find(params[:id])
    if current_user == @yes_list.user
      YesList.destroy(params[:id])
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Saved.' }
      end
    else
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Not Allowed.'
                  render action: 'error'}
      end
    end
  end

  def toggle
    @yes_list = YesList.find(params[:id])
    if current_user == @yes_list.user
      if @yes_list.match.downcase == 'yes'
        @yes_list.update(match:'NO')
      elsif @yes_list.match.downcase == 'no'
        @yes_list.update(match:'YES')
      end
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Saved.' }
      end
    else
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Not Allowed.'
                  render action: 'error'}
      end
    end
  end

  private
  def list_params
    params.require(:yes_list).permit(:user_id,:target_id,:match,:id)
  end

  def search_params
    if params[:name].blank? and params[:match].blank?
      Rails.logger.debug('Trigger A')
      [User.joins(:yes_lists).select("users.*, count(yes_lists.id) as ycount").group("users.id").order("ycount DESC")].flatten
    else
      Rails.logger.debug('Trigger B')
      params[:name].blank? ? users = User.all : users = User.students.search(params[:name])
      @match = params[:match]
      @count = users.joins(:yes_lists).group(:user_id).count.count
      [users.joins(:yes_lists).select("users.*, count(yes_lists.id) as ycount").group("users.id").order("ycount DESC")].flatten
    end
  end

end

app/helpers/yes_lists_helper.rb
module YesListsHelper
  def index

  end
end

app/views/yes_lists/_new.html.erb
<%= form_for @yes_list, remote: true do |f| %>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.collection_select :target_id, User.students.order(lname:'ASC')-current_user.marked-[current_user], :id, :tag, required: true %>
    <%= f.select :match, %W(YES NO), autofocus:true, placeholder: 'Choose One' %>
    <%= f.submit 'Save', class:'submit-btn' %>
    <small><%= link_to 'Cancel', '#', id:'cancel-add', remote: true %></small>

<% end %>

app/views/yes_lists/_users.html.erb
<% @users.each do |u| %>
    <span id="user-<%=u.id%>">
      <div class="image">
        <%= image_tag(u.avatar.url(:frame)) %>
      </div>
      <div class="details">
        <%= u.fullname %><br/>
        <%= u.program %><br/>
        <%= "#{u.fname} prefers working with you." if u.likes(current_user) %><br/>
        <%= link_to 'YES', yes_lists_path(yes_list:{user_id:current_user.id,target_id:u.id,match:'YES'}), method: :post, remote: true, class:'submit-btn' %>
        <%= link_to 'NO', yes_lists_path(yes_list:{user_id:current_user.id,target_id:u.id,match:'NO'}), method: :post, remote: true, class:'submit-btn' %>
      </div>
      <hr/>
    </span>
<% end %>

app/views/yes_lists/_users_admin_view.html.erb
<% @users.each do |u| %>
    <% @match.present? ? @yes_lists = u.yes_lists.where(match:@match) : @yes_lists = u.yes_lists %>
    <h4>
      <%= link_to u do %>
          <%= image_tag u.avatar.url(:thumb), size:'20x20', class:'round' %>
          <%= "#{u.fullname} - #{pluralize(@yes_lists.count, 'Choice')}" %>
      <% end %>
    </h4>
    <small><%= link_to 'VIEW', '#', class:'view' %></small>
    <div class="hate-list"><%= render 'yes_lists' %></div>
    <hr/>
<% end %>

app/views/yes_lists/_yes_list.html.erb
<p id="yes-list-<%= @yes_list.id %>">
  <%= image_tag(@yes_list.target.avatar.url(:thumb), size:'20x20', class:'round') %>
  <%= "#{@yes_list.target.fullname} - " %>
  <%= @yes_list.match == 'YES' ? 'YES':link_to('YES',toggle_yes_list_path(@yes_list.id),remote:true, class: 'submit-btn') %>
  <%= @yes_list.match == 'NO' ? 'NO':link_to('NO',toggle_yes_list_path(@yes_list.id),remote:true, class: 'submit-btn') %>
  <%= !@yes_list.match ? 'Don\'t Care':link_to('Don\'t Care',@yes_list, method: :delete, data: {confirm: 'Are You Sure?'},remote:true, class: 'submit-btn') %>
<br/>

app/views/yes_lists/_yes_lists.html.erb
<% @yes_lists.each do |ylist| %>

    <% if current_user.admin %>
        <p id="yes-list-<%= ylist.id %>">
          <%= link_to ylist.target do %>
          <%= image_tag(ylist.target.avatar.url(:thumb), size:'20x20', class:'round') %>
          <%= "#{ylist.target.fullname} - #{ylist.match}" %>
          <% end %>
        </p>
    <% else %>
        <p id="yes-list-<%= ylist.id %>">
          <%= link_to ylist.target do %>
              <%= image_tag(ylist.target.avatar.url(:thumb), size:'20x20', class:'round') %>
              <%= "#{ylist.target.fullname} - "%>
          <% end %>
          <%= ylist.match == 'YES' ? 'YES':link_to('YES',toggle_yes_list_path(ylist.id),remote:true, class: 'submit-btn') %>
          <%= ylist.match == 'NO' ? 'NO':link_to('NO',toggle_yes_list_path(ylist.id),remote:true, class: 'submit-btn') %>
          <%= !ylist.match ? 'Don\'t Care':link_to('Don\'t Care',ylist, method: :delete, data: {confirm: 'This will detele this preference. Are You Sure?'},remote:true, class: 'submit-btn') %>
        </p>
    <% end %>
<% end %>

app/views/yes_lists/create.js.erb
$('#new_yes_list').remove();
$('.list-block').append("<%= j render('yes_list') %>");
$("#user-<%=@yes_list.target_id %>").remove();
$('#none-message').hide();
$('#add-block').show();

$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});

<% flash.clear %>

app/views/yes_lists/destroy.js.erb
$('#yes-list-<%= @yes_list.id %>').remove();

<% if current_user.yes_lists.count < 1 %>
$("#none-message").show();
<% end %>

$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});

<% flash.clear %>

app/views/yes_lists/error.js.erb
$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});

<% flash.clear %>

app/views/yes_lists/index.html.erb
<% content_for :title, 'Y-List' %>
<div class="yes-lists">
  <div class="wrapper">

    <% if current_user.admin %>
        <div class="main-block">
          <h1>Student Working Preferences</h1>

          <div class="yes-list-chart-1">
            <p>The Most Difficult</p>
            <%= column_chart difficult_graph_yes_lists_path,library:{backgroundColor:'transparent', vAxis:{title:"No. of 'NO's Selected"}}, id:'difficult-chart' %>
          </div>
          <div class="yes-list-chart-2">
            <p>The Most Hated</p>
            <%= column_chart hated_graph_yes_lists_path, id:'hated-chart', library:{backgroundColor:'transparent', vAxis:{title:"No. of students who selected 'NO'"}} %>
          </div>

          <%= form_tag yes_lists_path, method: 'get' do %>
              <%= text_field_tag :name, params[:name],autofocus: true, placeholder: 'Enter Name', class: 'txt-fld' %>
              <%= select_tag :match, options_for_select([['YES'],['NO']],selected:params[:match]),include_blank:'None' %>
              <%= submit_tag 'Filter' %>
          <% end %>

          <%= "#{pluralize(@count,'student')} with Working Preferences." %>

          <hr/>
          <div class="users-admin-view" id="infinite-coffee-scroll">
            <%= render 'users_admin_view' %>
          </div>
          <%= will_paginate @users %>

        </div>
    <% else %>
        <div class="main-block">
          <h1>Your Yes-List</h1>

        </div>

        <div class="list-block">
          <p> User Name - Your Working Preference</p>
          <% if @yes_lists.any? %>
              <%= render 'yes_lists' %>
          <% else %>
              <p id="none-message"> You have not marked any user-compatibility preferences.</p>
          <% end %>
        </div>
        <%= will_paginate @yes_lists %>

        <hr/>

        <div class="add-block">
          <%= link_to 'Quick Add', new_yes_list_path, class:'submit-btn', remote: true, id:'add-block' %>
          <hr/>
        </div>
        <div class="all-users" id="infinite-coffee-scroll">
          <%= render 'users' %>
        </div>
        <%= will_paginate @users %>
    <% end %>
  </div>
</div>

app/views/yes_lists/index.js.erb
$('.users-admin-view').append("<%= j render 'users_admin_view' %>");

$('.all-users').append('<%= j render 'users' %>');
<% if @users.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @users %>');
<% else %>
$('#infinite-coffee-scroll').off('scroll');
$('.pagination ').html('<i>-fin-</i>');
<% end %>

app/views/yes_lists/new.js.erb
$('#add-block').hide().after("<%= j render ('new') %>");

$('#cancel-add').click(function(){
    $('#new_yes_list').remove();
    $('#add-block').show();
});

app/views/yes_lists/toggle.js.erb
$('#yes-list-<%= @yes_list.id %>').replaceWith("<%= j render ('yes_list') %>");

$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});

<% flash.clear %>