config/routes.rb
Rails.application.routes.draw do

  devise_for :users#, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    match 'admin/make_admin' => 'admin#make_admin', as: :admin_make_admin, via: [:get]
    match 'admin/get_pass' => 'admin#get_pass', as: :admin_get_pass, via: [:get]

  resources :admin, only: [:edit, :update] do
    get :make_admin, :get_pass
  end

  resources :competitions do
    collection do
      get :select_team, :join_comp, :leave_comp
    end
  end

  resources :invites, only: [:new, :create, :destroy] do
    collection do
      get :mass_invite
    end
  end

  resources :members, only: [:destroy, :new, :create] do
    collection do
      get :mass_add
    end
    member do
      get :join
    end
  end

  resources :notifications, only: [:index, :show]

  resources :preferences, only: [:edit, :update]
  resources :programs

  resources :simulations, only: [:index, :new] do
    collection do
      get :team_skills, :remove_member, :search
    end
    member do
      get :user_stats
    end
  end

  resources :skills do
    collection do
      get :category_skills, :indi_skills
    end
  end

  resources :teams do
    collection do
      get :mine
      post :transfer
    end
  end

  resources :users do
    collection do
      get :dashboard, :edit_avatar, :edit_password
      post  :update_password
    end
    member do
      get :column_graph, :indi_graph, :skill_graph
    end
  end

  resources :user_skills, only: [:create, :update, :index] do
    collection do
      patch :update
    end
  end

  get 'welcome/home'
  get 'welcome/contact_us'
  get 'welcome/about_us'

  resources :yes_lists do
    collection do
      get :difficult_graph, :hated_graph
    end
    member do
      get :toggle
    end

  end

  root to: 'welcome#home'
end


####
# get 'yes_lists/:id/toggle' => 'yes_lists#toggle', as: :toggle_yes_lists, via: [:get]
# match 'difficult_graph/yes_lists' => 'yes_lists#difficult_graph', as: :difficult_graph_yes_lists, via: [:get]
# match 'hated_graph/yes_lists' => 'yes_lists#hated_graph', as: :hated_graph_yes_lists, via: [:get]


####
# stuff transfered under the resources blocks
# match 'team_skills/simulations' => 'simulations#team_skills', as: :simulations_team_skills, via: [:get]
# match 'search/simulations' => 'simulations#search', as: :simulations_search, via: [:get]
# match 'remove_member/simulations' => 'simulations#remove_member', as: :simulations_remove_member, via: [:get]
# match 'user_stats/:id/simulations' => 'simulations#user_stats', as: :simulations_user_stats, via: [:get]

# Additional routes.
# get 'members/:id/join' => 'members#join', as: :members_join, via: [:get]
# get 'welcome/home'
# get 'welcome/contact_us'
# get 'welcome/about_us'

# match 'users/:id/edit_password' => 'users#edit_password', as: :user_edit_password, via: [:get]
# match 'users/update_password' => 'users#update_password', as: :user_update_password, via: [:post]
# match 'user/dashboard' => 'users#dashboard', as: :user_dashboard, via: [:get]
# match 'user/edit_avatar' => 'users#edit_avatar', as: :user_edit_avatar, via: [:get]
# match 'column_graph/:id/users' => 'users#column_graph', as: :column_graph_users, via: [:get]
# match 'indi_graph/:id/users' => 'users#indi_graph', as: :indi_graph_users, via: [:get]

# match 'pie_chart/skills' => 'skills#pie_chart', as: :pie_chart_skills, via: [:get]
# get 'yes_lists/:id/toggle' => 'yes_lists#toggle', as: :toggle_yes_lists, via: [:get]
# match 'difficult_graph/yes_lists' => 'yes_lists#difficult_graph', as: :difficult_graph_yes_lists, via: [:get]
# match 'hated_graph/yes_lists' => 'yes_lists#hated_graph', as: :hated_graph_yes_lists, via: [:get]
# match 'select_team/competitions' => 'competitions#select_team', as: :select_team_competitions, via: [:get]
# match 'join_comp/competitions' => 'competitions#join_comp', as: :join_comp_competitions, via: [:get]
# match 'leave_comp/competitions' => 'competitions#leave_comp', as: :leave_comp_competitions, via: [:get]

# get 'mine/users' => 'users#mine', as: :teams_mine, via: [:get]

# match 'admin/make_admin' => 'admin#make_admin', as: :admin_make_admin, via: [:get]
# match 'admin/get_pass' => 'admin#get_pass', as: :admin_get_pass, via: [:get]

# match 'mass_invite/invites' => 'invites#mass_invite', as: :invites_mass_invite, via: [:get]


#####
  # Probably do not need any of this nonsense:-
  # match 'members/join' => 'members#join', as: :members_join, via: [:get]
  # match 'members/leave' => 'members#leave', as: :members_leave, via: [:get]
  # match 'invites/invite' => 'invites#invite', as: :invites_invite, via: [:get]
  # match 'invites/send' => 'invites#send', as: :invites_send, via: [:get]
  # match 'invites/reject' => 'invites#reject', as: :invites_reject, via: [:get]

  # UserSkills default routes list -> managed under 'resources'
  # get 'user_skills/index'
  # get 'user_skills/new'
  # match 'user_skills/create' => 'user_skills#create', as: :user_skills_create, via: [:post]
  # get 'user_skills/edit'
  # get 'user_skills/update'
  # get 'user_skills/destroy'

  # Competitions default routes list -> managed under 'resources'
  # get 'competitions/index'
  # get 'competitions/:id/show' => 'competitions#show', as: :competition, via: [:get]
  # get 'competitions/new'
  # match 'competitions/create' => 'competitions#create', as: :competitions_create, via: [:post]
  # get 'competitions/edit'
  # get 'competitions/update'
  # get 'competitions/destroy'

  # Users default routes list -> managed under 'resources'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/edit_password' => 'users#edit_password'

  # YesLists default routes list -> managed under 'resources'
  # get 'yes_lists/new'
  # get 'yes_lists/create'
  # get 'yes_lists/index'
  # get 'yes_lists/edit'
  # get 'yes_lists/update'
  # get 'yes_lists/destroy'

app/models/competition.rb
class Competition < ApplicationRecord

  # attr_accessor :name, :description
  #
  # belongs_to :creator, :class_name => :user, foreign_key: :user_id

  validates :name, presence: true

  has_many :comp_teams, dependent: :destroy
  has_many :teams, through: :comp_teams

  belongs_to :creator, class_name: 'User'

  scope :latest, -> {order(created_at:'DESC')}

  def participant(user)
    self.teams.exists?Team.where(:id => Member.where(user:user).select(:team_id))
  end

  def participants
    self.teams.collect{|t|t.users}.flatten
  end

  def self.mine(user)
    where(:id => CompTeam.where(:team_id => user.teams.pluck(:id)).pluck(:competition_id))
  end

  def user_team(user)
    user.teams.where(:id => self.comp_teams.pluck(:team_id) ).first
  end

  def full_url
    if url.include?'http'
      url
    else
      'http://'+url
    end
  end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :check_authorization, only: [:edit, :update, :destroy]

  def index
    @competitions = Competition.latest.paginate(page: params[:page], per_page: 10)
  end

  def show
    @competition = Competition.find(params[:id])
    respond_to do |format|
      format.html { redirect_to competitions_path}
      format.js
    end
  end

  def new
    @competition = Competition.new
    @competition.creator_id = current_user.id
  end

  def create
    @competition = Competition.new(comp_params)
    if @competition.save
      redirect_to competition_path(@competition), notice: 'New Competition has been added.'
    else
      redirect_back(fallback_location: competitions_new_path, notice: 'Failed. Please try again.')
    end
  end

  def edit
    @competition = Competition.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @competition = Competition.find(params[:id])
    if @competition.update_attributes(comp_params)
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Updated.' }
      end
    else
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Update Failed.'
                  render action: 'error' }
      end
    end
  end

  def destroy
    @competition = Competition.find(params[:id]).destroy
    respond_to do |format|
      format.html {redirect_to(competitions_path, notice: 'Deleted.')}
      format.js { flash[:notice] = 'Deleted.' }
    end
  end

  def select_team
    @teams = current_user.teams
    @competition = Competition.find(params[:competition])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def join_comp
    @competition = Competition.find(params[:competition])
    if @comp_team.save
      respond_to do |format|
        format.html
        format.js { flash[:notice] = "You are participating in #{@comp_team.competition.name} with Team #{@comp_team.team.name}." }
      end
    else
      respond_to do |format|
        format.html
        format.js { flash[:notice] = 'Unable to add team to competition.'
                  render action: 'error' }
      end
    end
  end

  def leave_comp
    @comp_team = CompTeam.where(competition:@competition, team:@team).first
    @comp_team.destroy
    respond_to do |format|
      format.html
      format.js { flash[:notice] = 'Your team has left this competition.' }
    end
  end

  private
  def comp_params
    params.require(:competition).permit(:name, :url,:creator_id, :description, :start, :date, :duration, :comp_type, :prize, :host)
  end

  def check_authorization
    @competition = Competition.find(params[:id])
    unless current_user.admin || current_user == @competition.creator
      redirect_to @competition, :notice => 'Authorization Error.'
    end
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper

  def show
    @team = @competition.user_team(current_user) if user_signed_in?
  end

  def join_comp
    @team = Team.find(params[:team][:id]) || Team.create(team_params)
    @comp_team = CompTeam.new(competition:@competition,team:@team)
  end

  def leave_comp
    @competition = Competition.find(params[:competition])
    @team = Team.find(params[:team])
  end
end

app/views/competitions/_competition.html.erb
<h4>Competition Information</h4>
<p>Name: <%= @competition.name %></p>
<p>Link: <%= @competition.url ? link_to(@competition.url, @competition.full_url) : 'None provided.' %></p>
<p>Description: <%= @competition.description || 'None Provided.' %></p>
<p>Start Date: <%= @competition.start ? @competition.start.strftime('%D %Y') : 'None Provided.' %></p>
<p>Duration: <%= @competition.duration || 'None Provided.' %></p>
<p>Type: <%= @competition.comp_type || 'None Provided.' %></p>
<p>Hosted By: <%= @competition.host || 'None Provided.' %></p>
<p>Prize: <%= @competition.prize || 'None Provided.' %></p>
<p>Added By: <%= link_to (image_tag(@competition.creator.avatar.url(:thumb),class:'image round') + (@competition.creator.fullname || 'None Provided.')), @competition.creator  %></p>
<div class="comp-edit">
  <% if user_signed_in? %>
    <% if current_user.admin || current_user == @competition.creator %>
        <small>
          <%= link_to 'Edit', edit_competition_path(@competition), remote: true, id:"edit-competition-#{@competition.id}" %>
          <%= link_to 'Delete', @competition, method: 'delete', data:{confirm: 'Are you sure?'} %>
        </small>
    <% end %>
  <% end %>
</div>

app/views/competitions/_edit.html.erb
<h4>Competition Information</h4>
<%= form_for @competition, remote: true do |f| %>

    <div class="data-fields">
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, placeholder: 'Competition Name' %>
    </div>
    <div class="data-fields">
      <%= f.label :url %>
      <%= f.text_field :url, autofocus: true, placeholder: 'http://source.com' %>
    </div>
    <div class="data-fields">
      <%= f.label :description %>
      <%= f.text_area :description, autofocus: true, placeholder: 'Competition Details' %>
    </div>
    <div class="data-fields">
      <%= f.label :host %>
      <%= f.text_field :host, autofocus: true %>
    </div>
    <div class="data-fields">
      <%= f.label :start_date %>
      <%= f.date_field :start, autofocus: true, placeholder: 'Competition Name' %>
    </div>
    <div class="data-fields">
      <%= f.label :type %>
      <%= f.select :comp_type, %w(24-Hour Standard), autofocus: true, selected: 'Standard' %>
    </div>
    <div class="data-fields">
      <%= f.label :duration, 'Duration (Days)' %>
      <%= f.number_field :duration, autofocus: true, placeholder: 'Days' %>
    </div>
    <div class="data-fields">
      <%= f.label :prize %>
      <%= f.text_field :prize, autofocus: true, placeholder: 'Leave blank if none.' %>
    </div>
    <div class="action-button">
      <%= f.submit 'Update', class: 'btn' %><br />
    </div>

    <div class="data-fields">
      <div class="ue">
        <small><%= link_to 'Cancel', '#', id:'cancel-edit' %></small>
      </div>
    </div>

<% end %>

app/views/competitions/_participate.html.erb
<div class="participate">
  <span class="submit-btn" id="participate-button"><%= 'Participate' %></span>
  <div id="choices" style="display: none">
    <%= link_to 'Select team', {controller:'competitions', action:'select_team', :competition => @competition.id}, remote: true, id:'select-button', class:'submit-btn' if current_user.teams.present? %>
    <%= link_to 'Create Team', mine_teams_path, id:'create-button', class:'submit-btn' %>

    <small id="participate-cancel" style="cursor: pointer"><%= 'Cancel' %></small>

  </div>
</div>

app/views/competitions/_select_team.html.erb
<%= form_tag join_comp_competitions_path, method: 'get',id:'team-form', remote: true do %>
    <%= hidden_field_tag 'competition', @competition.id %>
    <%= collection_select :team, :id, @teams, :id, :name, class:'drop-down' %>
    <%= submit_tag 'Save', class:'submit-btn' %> <small><%= link_to 'Cancel', '#', id:'cancel-select'%></small>
<% end %>

app/views/competitions/_show.html.erb
<% content_for :title, @competition.name %>

<div class="competitions">
  <div class="info">
    <div class="data-fields">
      <%= render 'competition' %>
    </div>
    <hr/>
    <% if user_signed_in? %>
      <div class="actions">
        <% if @team %>
            <%= render 'team' %>
        <% else %>
            <%= render 'participate' %>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/competitions/_team.html.erb
<div class="team-show">
  <%= 'Your Participating Team: ' %><%= link_to @team.name, @team %>
  <small><%= link_to '| Leave Competition', { controller: 'competitions', action: 'leave_comp', team: @team.id, competition: @competition.id }, data: {confirm:'Are You Sure?'}, remote:true, id:'leave-competition' if @team.is_lead(current_user) %></small>
</div>

app/views/competitions/edit.js.erb
$('.data-fields').empty().append("<%= j render('edit') %>");

$('#cancel-edit').click(function(){
    $('.data-fields').empty().append("<%= j render('competition') %>");
});

app/views/competitions/error.js.erb
$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});

app/views/competitions/index.html.erb
<% content_for :title, 'Competitions' %>
<div class="competitions">
  <% unless user_signed_in? %>
      <div class="login-control">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.label '', 'Username' %><br/>
              <%= f.email_field :email, autofocus: true, placeholder:'Gator.Link@ufl.edu', class:'login-field' %><br>
              <%= f.label '', 'Password' %><br/>
              <%= f.password_field :password, autocomplete: "off", placeholder:'-Password-', class:'login-field' %><br>
              <p></p>
              <%= f.submit "LOG IN", class:'login-button' %>
            </div>

        <%end%>
      </div>
  <% end %>
  <div class="wrapper">
    <h1>Open Case Competitions</h1>
    <% if @competitions.any? %>
        <div id="competitions-list">
          <%= render('competitions') %>
        </div>
    <% else %>
      <%= 'No case competitions added yet.' %>
    <% end %>
  </div>
  <div class="details">
    <br/>
    <br/>
    <p>Select Competition for Details.</p>
  </div>
</div>

app/views/competitions/leave_comp.js.erb
$('.team-show').empty();
$('.participate').show();

$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});

app/views/competitions/select_team.js.erb
$('#choices').hide().after("<%= j render('select_team') %>");
$('#cancel-select').click(function(){
    $('#team-form').remove();
    $('#choices').show();
});

app/views/competitions/show.js.erb
$('.details').empty().append("<%= j render('show') %>");

$(document).ready(function(){
    $('#participate-button').click(function(){
        $('#participate-button').toggle();
        $('#choices').toggle();
    });
    $('#participate-cancel').click(function(){
        $('#participate-button').toggle();
        $('#choices').toggle();
    });
});

app/views/competitions/update.js.erb
$('.data-fields').empty().append("<%= j render('competition') %>");

$("#notice-message").html("<%= flash[:notice] %>").show();
$(".error").show();
$(function () {
    setTimeout(function () {
        $("#notice-message").fadeOut('slow', function () {
            $(this).hide();
        })
        $(".error").fadeOut('slow',function() {
            $(this).hide();
        })
    }, 2000);
});