config/routes.rb
Rails.application.routes.draw do

  devise_for :users#, controllers: {registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    match 'admin/make_admin' => 'admin#make_admin', as: :admin_make_admin, via: [:get]
    match 'admin/get_pass' => 'admin#get_pass', as: :admin_get_pass, via: [:get]

  resources :admin, only: [:edit, :update] do
    get :make_admin, :get_pass
  end

  resources :competitions do
    collection do
      get :select_team, :join_comp, :leave_comp
    end
  end

  resources :invites, only: [:new, :create, :destroy] do
    collection do
      get :mass_invite
    end
  end

  resources :members, only: [:destroy, :new, :create] do
    collection do
      get :mass_add
    end
    member do
      get :join
    end
  end

  resources :notifications, only: [:index, :show]

  resources :preferences, only: [:edit, :update]
  resources :programs

  resources :simulations, only: [:index, :new] do
    collection do
      get :team_skills, :remove_member, :search
    end
    member do
      get :user_stats
    end
  end

  resources :skills do
    collection do
      get :category_skills, :indi_skills
    end
  end

  resources :teams do
    collection do
      get :mine
      post :transfer
    end
  end

  resources :users do
    collection do
      get :dashboard, :edit_avatar, :edit_password
      post  :update_password
    end
    member do
      get :column_graph, :indi_graph, :skill_graph
    end
  end

  resources :user_skills, only: [:create, :update, :index] do
    collection do
      patch :update
    end
  end

  get 'welcome/home'
  get 'welcome/contact_us'
  get 'welcome/about_us'

  resources :yes_lists do
    collection do
      get :difficult_graph, :hated_graph
    end
    member do
      get :toggle
    end

  end

  root to: 'welcome#home'
end


####
# get 'yes_lists/:id/toggle' => 'yes_lists#toggle', as: :toggle_yes_lists, via: [:get]
# match 'difficult_graph/yes_lists' => 'yes_lists#difficult_graph', as: :difficult_graph_yes_lists, via: [:get]
# match 'hated_graph/yes_lists' => 'yes_lists#hated_graph', as: :hated_graph_yes_lists, via: [:get]


####
# stuff transfered under the resources blocks
# match 'team_skills/simulations' => 'simulations#team_skills', as: :simulations_team_skills, via: [:get]
# match 'search/simulations' => 'simulations#search', as: :simulations_search, via: [:get]
# match 'remove_member/simulations' => 'simulations#remove_member', as: :simulations_remove_member, via: [:get]
# match 'user_stats/:id/simulations' => 'simulations#user_stats', as: :simulations_user_stats, via: [:get]

# Additional routes.
# get 'members/:id/join' => 'members#join', as: :members_join, via: [:get]
# get 'welcome/home'
# get 'welcome/contact_us'
# get 'welcome/about_us'

# match 'users/:id/edit_password' => 'users#edit_password', as: :user_edit_password, via: [:get]
# match 'users/update_password' => 'users#update_password', as: :user_update_password, via: [:post]
# match 'user/dashboard' => 'users#dashboard', as: :user_dashboard, via: [:get]
# match 'user/edit_avatar' => 'users#edit_avatar', as: :user_edit_avatar, via: [:get]
# match 'column_graph/:id/users' => 'users#column_graph', as: :column_graph_users, via: [:get]
# match 'indi_graph/:id/users' => 'users#indi_graph', as: :indi_graph_users, via: [:get]

# match 'pie_chart/skills' => 'skills#pie_chart', as: :pie_chart_skills, via: [:get]
# get 'yes_lists/:id/toggle' => 'yes_lists#toggle', as: :toggle_yes_lists, via: [:get]
# match 'difficult_graph/yes_lists' => 'yes_lists#difficult_graph', as: :difficult_graph_yes_lists, via: [:get]
# match 'hated_graph/yes_lists' => 'yes_lists#hated_graph', as: :hated_graph_yes_lists, via: [:get]
# match 'select_team/competitions' => 'competitions#select_team', as: :select_team_competitions, via: [:get]
# match 'join_comp/competitions' => 'competitions#join_comp', as: :join_comp_competitions, via: [:get]
# match 'leave_comp/competitions' => 'competitions#leave_comp', as: :leave_comp_competitions, via: [:get]

# get 'mine/users' => 'users#mine', as: :teams_mine, via: [:get]

# match 'admin/make_admin' => 'admin#make_admin', as: :admin_make_admin, via: [:get]
# match 'admin/get_pass' => 'admin#get_pass', as: :admin_get_pass, via: [:get]

# match 'mass_invite/invites' => 'invites#mass_invite', as: :invites_mass_invite, via: [:get]


#####
  # Probably do not need any of this nonsense:-
  # match 'members/join' => 'members#join', as: :members_join, via: [:get]
  # match 'members/leave' => 'members#leave', as: :members_leave, via: [:get]
  # match 'invites/invite' => 'invites#invite', as: :invites_invite, via: [:get]
  # match 'invites/send' => 'invites#send', as: :invites_send, via: [:get]
  # match 'invites/reject' => 'invites#reject', as: :invites_reject, via: [:get]

  # UserSkills default routes list -> managed under 'resources'
  # get 'user_skills/index'
  # get 'user_skills/new'
  # match 'user_skills/create' => 'user_skills#create', as: :user_skills_create, via: [:post]
  # get 'user_skills/edit'
  # get 'user_skills/update'
  # get 'user_skills/destroy'

  # Competitions default routes list -> managed under 'resources'
  # get 'competitions/index'
  # get 'competitions/:id/show' => 'competitions#show', as: :competition, via: [:get]
  # get 'competitions/new'
  # match 'competitions/create' => 'competitions#create', as: :competitions_create, via: [:post]
  # get 'competitions/edit'
  # get 'competitions/update'
  # get 'competitions/destroy'

  # Users default routes list -> managed under 'resources'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/edit_password' => 'users#edit_password'

  # YesLists default routes list -> managed under 'resources'
  # get 'yes_lists/new'
  # get 'yes_lists/create'
  # get 'yes_lists/index'
  # get 'yes_lists/edit'
  # get 'yes_lists/update'
  # get 'yes_lists/destroy'

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def contact_us
  end

  def about_us
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/welcome/_footer.html.erb
<div class="footer-box">
  <div class="links">
    <ul>
      <!--<li><%= link_to 'About Us', '/welcome/about_us' %></li>-->
      <li><%= link_to 'Copyright © 2017 Effari All Rights Reserved', '#' %></li>
      <!--<li><%= link_to 'Contact Us', '/welcome/contact_us' %></li>-->
    </ul>
  </div>
</div>

app/views/welcome/_navbar.html.erb
<section class="navigation">
  <div class="nav-container">
    <div class="brand">
      <div class="logo"><%= image_tag('icons/UFsig_small.gif') %></div>
      <div class="items" id="screen"><%= link_to 'WARRINGTON SCHOOL OF BUSINESS', 'http://warrington.ufl.edu/' %></div>
      <div class="items" id="mobile"><%= link_to 'WSB', 'http://warrington.ufl.edu/' %></div>
    </div>
    <nav>
      <div class="nav-mobile">
        <!-- This is the toggle element -->
        <section id="nav-toggle"><%= link_to '', '#' %><span></span><span></span><span></span></section>
      </div>
      <ul class="nav-list">
        <!-- After Sign In -->
        <% if user_signed_in? %>
            <li><%= link_to 'Home', '/welcome/home' %></li>
            <li><%= (current_user.fname && current_user.fname !='') ? link_to(current_user.fname, '#') : link_to(current_user.fullname, '#') %>
              <ul class="nav-dropdown">
                <li><%= link_to 'Profile', current_user, :method => 'get' %></li>
                <li><%= link_to 'Logout', '/users/sign_out', :method => 'delete' %></li>
              </ul>
            </li>
            <li><%= link_to image_tag('icons/notification.png',size:'20x20', id:'notif-icon'), '#',id:"notif-dropdown" %>
              <ul class="nav-dropdown notif-dropdown">
                <li id="no-notifications"><%= link_to 'No new notifications', '#' unless current_user.notifications.unread.present? %></li>
                <div id="notifications"><%= render('notifications/new_notifications') %></div>
              </ul>
            </li>
        <% else %> <!-- If not signed in -->
            <li><%= link_to 'Home', '/welcome/home' %></li>
            <li><%= link_to 'Sign Up', '/users/sign_up' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</section>

app/views/welcome/_sidebar.html.erb
<div class="side-bar-open" id="open-side-bar"></div>
<div class="side-bar-close" id="close-side-bar"></div>
<div class="sidebar-container">
  <div class="wrapper">

    <% if user_signed_in? %>

    <div class="cover">
      <div class="image">
        <%= link_to(image_tag(current_user.avatar.url(:display), size:'80x80' , class: 'round'), edit_avatar_users_path , remote:true, id:'edit-avatar') %>
      </div>
    </div>

      <div class="settings">
        <div class="tabs">
          <ul>
            <%= link_to dashboard_users_path do %>
                <li>Dashboard</li>
            <% end %>
            <% if current_user.admin %>
                <%= link_to skills_path do %>
                    <li>Skill List</li>
                <% end %>
                <%= link_to programs_path do %>
                    <li>Program List</li>
                <% end %>
                <%= link_to teams_path do %>
                    <li>Search Teams</li>
                <% end %>
                <%= link_to mine_teams_path do %>
                    <li>My Teams</li>
                <% end %>
                <br/>
            <% end %>
            <%= link_to yes_lists_path do %>
                <li>The Yes-List</li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="tasks">
      <div class="tabs">
        <ul>

          <%= link_to users_path do %>
              <li>All Students</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about_us.html.erb
<h1>Welcome#about_us</h1>
<p>Find me in app/views/welcome/about_us.html.erb</p>

app/views/welcome/contact_us.html.erb
<h1>Welcome#contact_us</h1>
<p>Find me in app/views/welcome/contact_us.html.erb</p>

app/views/welcome/home.html.erb
<%= content_for :title, 'Home' %>
<% unless user_signed_in? %>
  <div class="login-control">
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="field">
          <%= f.label '', 'Username' %><br/>
          <%= f.email_field :email, autofocus: true, placeholder:'Gator.Link@ufl.edu', class:'login-field' %><br>
          <%= f.label '', 'Password' %><br/>
          <%= f.password_field :password, autocomplete: "off", placeholder:'-Password-', class:'login-field' %><br>
          <p></p>
          <%= f.submit "LOG IN", class:'login-button' %>
        </div>

    <%end%>
  </div>
<% end %>

<div class="temp-content" style="margin-top:5em">
  <div class="platform" style="padding-top: 5em;padding-bottom: 5em;">
    <h1>
      University of Florida - GBCS
    </h1>
    <h2>
      Case Competition Team Builder
    </h2>
    Welcome to UFGBCS Team Builder.
    <%= user_signed_in? ? 'You are already Signed In' : 'Please Sign Up / Login to begin.' %> <br/><br/>
    Do ensure your details are always up-to-date to facilitate the selection process.
  </div>
</div>